Allow alternative comment start pattern for tag-like delimiters

diff --git a/shinclude b/shinclude
--- a/shinclude
+++ b/shinclude
@@ -357,7 +357,7 @@ shinclude::block::RENDER() {
         dollarone="-p '$p' $dollarone"
     done
     eval set -- "$dollarone"
-    shlog -l debug "shrender $*"
+    shlog -l debug "shrender '$1' '$2' '$3' '$4'"
     shrender "$@"
 }
 # #### `$EXT_TO_COMMENT_STYLE`
@@ -379,6 +379,15 @@ export EXT_TO_COMMENT_STYLE=()
 #
 typeset -A COMMENT_STYLE_START
 export COMMENT_STYLE_START=()
+
+# #### `$COMMENT_STYLE_START_ALTERNATIVE`
+#
+# Associative array of comment start strings for select languages
+#
+#       COMMENT_STYLE_START_ALTERNATIVE[html]="<!--"
+#
+typeset -A COMMENT_STYLE_START_ALTERNATIVE
+export COMMENT_STYLE_START_ALTERNATIVE=()
 
 # #### `$COMMENT_STYLE_END`
 #
@@ -560,53 +569,70 @@ _detect_comment_style() {
 
 # shellcheck disable=2094
 shinclude::read_lines() {
-    local pass line begin end blocktype blockargs block infile
-    pass=$1
-    infile=$2
-    IFS=$'\n'
-    while read -r line;do
-      if [[ "$line" = "$COMMENT_START BEGIN-"* ]];then
-          begin="$line"
+  local pass line begin end blocktype blockargs block infile
+  pass=$1
+  infile=$2
+  IFS=$'\n'
+  local alternativeStartPattern
+  alternativeStartPattern="${COMMENT_START_ALTERNATIVE:-$COMMENT_START}"
 
-          blocktype="${begin:${#COMMENT_START}:${#line}}"
-          blocktype="${blocktype##*BEGIN-}"
-          blocktype="${blocktype%$COMMENT_END}"
-          blocktype="${blocktype%% *}"
+  while read -r line;do
+    # shlog -l info "line='${line:0:10}'"
+    local matched=
+    # shlog -l info "line='${line:10}' $COMMENT_START='$$COMMENT_START'"
+    # shlog -l info "foo=$foo line=$line"
+    if [[ "$line" = "$COMMENT_START BEGIN-"* ]];then
+        matched=true
+    fi
+    # shlog -l info "$COMMENT_START=$$COMMENT_START"
 
-          blockargs="${begin:${#COMMENT_START}:${#line}}"
-          blockargs="${blockargs#*BEGIN-$blocktype}"
-          blockargs="${blockargs# }"
-          blockargs="${blockargs% $COMMENT_END}"
+    if [[ $matched = true ]];then
+      begin="$line"
 
-          block=""
-          while
-              read -r line \
-              && [[ "$line" != "$COMMENT_START END-$blocktype"* \
-              && "$line" != *"END-$blocktype $COMMENT_END"   ]]
-          do
-              printf -v block "%s\n%s" "$block" "$line"
-          done
-          if ! declare -f -F "shinclude::block::$blocktype" >/dev/null;then
-              shlog -l error -x 2 "No such block type '$blocktype'"
-          fi
-          if [[ ${BLOCK_PASS[$blocktype]} != $pass ]];then
-              shlog -l debug "PASS $pass: SKIP '$blocktype' '$blockargs'"
-              printf "%s%s\n%s\n" "$begin" "$block" "$line"
-              continue;
-          fi
-          shlog -l debug "PASS $pass: RUN $blocktype '$blockargs'"
-          shlog -l trace "PASS $pass: RUN $blocktype '$blockargs' '$block'"
-          newblock="$("shinclude::block::$blocktype" "$blockargs" "$block" "$infile")"
-          ret=$?
-          if [[ $ret != 0 ]];then
-              shlog -l error -x 2 "$ret: Error running '$blocktype' '$blockargs'"
-          fi
-          printf "%s\n%s\n\n%s\n" "$begin" "$newblock" "$line"
-      else
-          shlog -l trace "PASS $pass: (ign) $line"
-          printf "%s\n" "$line"
+      blocktype="${begin:${#COMMENT_START}:${#line}}"
+      blocktype="${blocktype##*BEGIN-}"
+      blocktype="${blocktype%$COMMENT_END}"
+      blocktype="${blocktype%% *}"
+
+      # shlog -l info "$COMMENT_START=$COMMENT_START alternativeStartPattern=$alternativeStartPattern"
+      # shlog -l info "blocktype=$blocktype"
+
+      blockargs="${begin:${#COMMENT_START}:${#line}}"
+      blockargs="${blockargs#*BEGIN-$blocktype}"
+      blockargs="${blockargs# }"
+      blockargs="${blockargs% $COMMENT_END}"
+      # shlog -l info "2 blockargs=$blockargs"
+
+      block=""
+      while
+        read -r line \
+          && [[ "$line" != "$alternativeStartPattern END-$blocktype"* \
+          && "$line" != *"END-$blocktype $COMMENT_END"   ]]
+      do
+        printf -v block "%s\n%s" "$block" "$line"
+      done
+      # shlog -l info ">>>> $block"
+      if ! declare -f -F "shinclude::block::$blocktype" >/dev/null;then
+        shlog -l error -x 2 "No such block type '$blocktype'"
       fi
-    done < "$infile"
+      if [[ ${BLOCK_PASS[$blocktype]} != $pass ]];then
+        shlog -l debug "PASS $pass: SKIP '$blocktype' '$blockargs'"
+        printf "%s%s\n%s\n" "$begin" "$block" "$line"
+        continue;
+      fi
+      shlog -l debug "PASS $pass: RUN $blocktype '$blockargs'"
+      shlog -l trace "PASS $pass: RUN $blocktype '$blockargs' '$block'"
+      newblock="$("shinclude::block::$blocktype" "$blockargs" "$block" "$infile")"
+      ret=$?
+      if [[ $ret != 0 ]];then
+        shlog -l error -x 2 "$ret: Error running '$blocktype' '$blockargs'"
+      fi
+      printf "%s\n%s\n\n%s\n" "$begin" "$newblock" "$line"
+    else
+      shlog -l trace "PASS $pass: (ign) $line"
+      printf "%s\n" "$line"
+    fi
+  done < "$infile"
 }
 # ### usage
 #
@@ -705,6 +731,17 @@ _parse_args() {
                 ##
                 COMMENT_START="$2"; shift
                 ;;
+            -csa|--comment-start-alternative)
+                ## ### -csa, --comment-start-alternative COMMENT_START_ALTERNATIVE
+                ##
+                ## Alternative comment start. Overrides language-specific comment start.
+                ##
+                ## Useful for vim folds
+                ##
+                ## See [COMMENT STYLES](#comment-styles).
+                ##
+                COMMENT_START_ALTERNATIVE="$2"; shift
+                ;;
             -ce|--comment-end)
                 ## ### -ce, --comment-end COMMENT_END
                 ##
@@ -758,9 +795,11 @@ _parse_args() {
         shlog -l error -x 2 "Unable to detect comment style."
     fi
     COMMENT_START=${COMMENT_START:-${COMMENT_STYLE_START[$COMMENT_STYLE]}}
+    COMMENT_START_ALTERNATIVE=${COMMENT_START_ALTERNATIVE:-${COMMENT_STYLE_START_ALTERNATIVE[$COMMENT_STYLE]}}
     COMMENT_END=${COMMENT_END:-${COMMENT_STYLE_END[$COMMENT_STYLE]}}
     shlog -l debug "COMMENT_STYLE=$COMMENT_STYLE"
     shlog -l debug "COMMENT_START=$COMMENT_START"
+    shlog -l debug "COMMENT_START_ALTERNATIVE=$COMMENT_START_ALTERNATIVE"
     shlog -l debug "COMMENT_END=$COMMENT_END"
     shlog -l debug "SHINCLUDE_INFILE=$SHINCLUDE_INFILE"
 }
